config/routes.rb
Rails.application.routes.draw do
  post 'sales', to: 'sales#create'
  get 'sales/new'
  get 'sales/:id', to: 'sales#done', as: 'done'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
    validates :cod, uniqueness: true
    validates :detail, presence: true
    validates :category, inclusion: { in: %w(uno dos tres cuatro cinco)}
    validates :discount, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 40 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def new
    
  end

  def create
    @sale = Sale.new(user_params)
    @sale.total = @sale.value - @sale.value * (@sale.discount.to_f/100)
    
    if @sale.tax == 0
      @sale.tax = 0
    else
      @sale.total = @sale.total* 1.19
      @sale.tax = 19
    end
    @sale.save
    #raise @sale.errors.inspect
    redirect_to done_path(@sale)
  end 
   
  def done
    @sale = Sale.find(params[:id])
  end


  private
  def user_params
    params.require(:sale).permit(:cod, :detail, :category, :value, :discount, :tax, :value)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registroventas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body class="mt-5">
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/sales/create.html.erb
<h1>Sales#create</h1>
<p>Find me in app/views/sales/create.html.erb</p>

app/views/sales/done.html.erb
<h1 class="mb-5 container"> ¡El registro fue almacenado con éxito!</h1>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <h2>Título de Venta</h2>
      <li>Cod</li>
      <li>Detail</li>
      <li>Category</li>
      <li>Value</li>
      <li>Discount</li>
      <li>Tax</li>
      <li>Total</li>
    </div>

    <div class="col-sm">
      <h2>Detalle de Venta</h2>
          <li><%= @sale.cod %> </li>
          <li><%= @sale.detail %> </li>
          <li><%= @sale.category %> </li>
          <li><%= @sale.value %> </li>
          <li><%= @sale.discount %> </li>
          <li><%= @sale.tax %> </li>
          <li><%= @sale.total %> </li>
    </div>
  </div>
</div>

<div> <%= link_to "Volver", sales_new_path, class:"btn btn-primary mt-5 ml-5"%> </div>

app/views/sales/new.html.erb
<%= form_with model: Sale.new, local: true do |f| %>
    <%= label_tag :cod, "Código:" %>
    <%= f.text_field :cod %>
    <%= label_tag :detail, "Detalle:" %>
    <%= f.text_area :detail%>
    <%= label_tag :category, "Categoria:"  %>
    <%= f.text_field :category %>
    <%= label_tag :value, "Valor:"  %>
    <%= f.text_field :value %>
    <%= label_tag :discount, "Descuento:"  %>
    <%= f.text_field :discount %>

    <%= label_tag :tax, "Exento de IVA" %>
    <%= f.check_box :tax %>

    <%= f.submit "Enviar" %>

<% end %>